name: ptc_quiz2
description: "PTC Quiz 2"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  animated_bottom_navigation_bar: ^1.3.3
  badges: ^3.1.2
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  credit_card_validator: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/images/test/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200